In [1]:
# Q1: Import NumPy and Check the Version
# Difficulty: L1

import numpy as np

result = np.__version__

print("Q1 Result:", result)


Q1 Result: 2.5.1


In [2]:
# Q2: Create a 1D Array
# Difficulty: L1

import numpy as np

result = np.arange(1,10)

print("Q2 Result:", result)


Q2 Result: [1 2 3 4 5 6 7 8 9]


In [4]:
# Q3: Create a Boolean Array
# Difficulty: L1

import numpy as np

result = np.ones((3,3),dtype=bool)

print("Q3 Result:\n", result)


Q3 Result:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# Q4: Extract Items That Satisfy a Condition
# Difficulty: L1

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

result = arr[arr%2 == 1]

print("Q4 Result:", result)


Q4 Result: [1 3 5 7 9]


In [11]:
# Q5: Replace Items That Satisfy a Condition
# Difficulty: L1

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1

result = arr

print("Q5 Result:", result)


Q5 Result: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [13]:
# Q6: Replace Items Without Affecting the Original Array
# Difficulty: L2

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr%2 == 1,-1,arr)

result = out

print("Q6 Result:", result)


Q6 Result: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [18]:
# Q7: Reshape an Array
# Difficulty: L1

import numpy as np
arr = np.arange(10)

result = arr.reshape(2,-1)

print("Q7 Result:\n", result)


Q7 Result:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
# Q8: Stack Two Arrays Vertically
# Difficulty: L2

import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
out = np.concatenate([a,b],axis=0)

result = out

print("Q8 Result:", result)


Q8 Result: [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
# Q9: Stack Two Arrays Horizontally
# Difficulty: L2

import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

result = np.concat([a,b],axis=1)

print("Q9 Result:", result)


Q9 Result: [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [32]:
# Q10: Generate Custom Sequences Without Hardcoding
# Difficulty: L2

import numpy as np
a = np.array([1,2,3])

result = np.repeat(np.repeat(a,3),3)
result = np.r_[np.repeat(a,3),np.tile(a,3)]

# arr = np.array([1, 2, 3])

# print(np.repeat(arr, 2))
# print(np.tile(arr, 2))
print("Q10 Result:", result)


Q10 Result: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [34]:
# Q11: Get Common Items Between Two Arrays
# Difficulty: L2

import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.intersect1d(a,b)

print("Q11 Result:", result)


Q11 Result: [2 4]


In [37]:
# Q12: Remove Items Present in Another Array
# Difficulty: L2

import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

result = np.setdiff1d(a,b)

print("Q12 Result:", result)


Q12 Result: [1 2 3 4]


In [38]:
# Q13: Find Positions Where Two Arrays Match
# Difficulty: L2

import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.where(a==b)

print("Q13 Result:", result)


Q13 Result: (array([1, 3, 5, 7]),)


In [41]:
# Q14: Extract Numbers Within a Given Range
# Difficulty: L2

import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
result = a[(a >= 5) & (a <= 10)]
# print(result)

# Method 2:
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])

# Method 3:
# index = np.where(np.logical_and(a>=5, a<=10))
# print(a[index])

print("Q14 Result:", result)


Q14 Result: [ 6  9 10]


In [43]:
# Q15: Vectorize a Scalar Function to Work on Arrays
# Difficulty: L3

import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair(a,b)

print("Q15 Result:", result)


Q15 Result: [6 7 9 8 9 7 5]


In [ ]:
# Q16: Swap Two Columns in a 2D Array
# Difficulty: L2

import numpy as np
arr = np.arange(9).reshape(3,3)

result = None

print("Q16 Result:", result)


In [ ]:
# Q17: Swap Two Rows in a 2D Array
# Difficulty: L2

import numpy as np
arr = np.arange(9).reshape(3,3)

result = None

print("Q17 Result:", result)


In [ ]:
# Q18: Reverse the Rows of a 2D Array
# Difficulty: L2

import numpy as np
arr = np.arange(9).reshape(3,3)

result = None

print("Q18 Result:", result)


In [ ]:
# Q19: Reverse the Columns of a 2D Array
# Difficulty: L2

import numpy as np
arr = np.arange(9).reshape(3,3)

result = None

print("Q19 Result:", result)


In [ ]:
# Q20: Create a 2D Array of Random Floats Between 5 and 10
# Difficulty: L2

import numpy as np

result = None

print("Q20 Result:", result)


In [ ]:
# Q21: Print Only 3 Decimal Places
# Difficulty: L1

import numpy as np
rand_arr = np.random.random((5,3))

result = None

print("Q21 Result:", result)


In [ ]:
# Q22: Suppress Scientific Notation in Print Output
# Difficulty: L1

import numpy as np
rand_arr = np.random.random((5,3))

result = None

print("Q22 Result:", result)


In [ ]:
# Q23: Limit the Number of Printed Items
# Difficulty: L1

import numpy as np
a = np.arange(15)
print(a)

result = None

print("Q23 Result:", result)


In [ ]:
# Q24: Print the Full Array Without Truncating
# Difficulty: L1

import numpy as np
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

result = None

print("Q24 Result:", result)


In [ ]:
# Q25: Import a Dataset With Mixed Types
# Difficulty: L2

import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

result = None

print("Q25 Result:", result)


In [ ]:
# Q26: Extract a Particular Column From a 1D Structured Array
# Difficulty: L2

result = None

print("Q26 Result:", result)


In [ ]:
# Q27: Convert a 1D Structured Array to a 2D Numeric Array
# Difficulty: L2

result = None

print("Q27 Result:", result)


In [ ]:
# Q28: Compute Mean, Median, and Standard Deviation
# Difficulty: L1

import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

result = None

print("Q28 Result:", result)


In [ ]:
# Q29: Normalize an Array to the 0-1 Range
# Difficulty: L2

import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

result = None

print("Q29 Result:", result)


In [ ]:
# Q30: Compute the Softmax Score
# Difficulty: L2

import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

result = None

print("Q30 Result:", result)


In [ ]:
# Q31: Find Percentile Scores
# Difficulty: L2

result = None

print("Q31 Result:", result)


In [ ]:
# Q32: Insert Values at Random Positions
# Difficulty: L3

result = None

print("Q32 Result:", result)


In [ ]:
# Q33: Find the Position of Missing Values
# Difficulty: L2

result = None

print("Q33 Result:", result)


In [ ]:
# Q34: Filter a NumPy Array Based on Multiple Conditions
# Difficulty: L2

result = None

print("Q34 Result:", result)


In [ ]:
# Q35: Drop Rows Containing Missing Values
# Difficulty: L2

result = None

print("Q35 Result:", result)


In [ ]:
# Q36: Find Correlation Between Two Columns
# Difficulty: L3

result = None

print("Q36 Result:", result)


In [ ]:
# Q37: Check for Missing Values in an Array
# Difficulty: L1

result = None

print("Q37 Result:", result)


In [ ]:
# Q38: Replace All Missing Values with Zero
# Difficulty: L1

result = None

print("Q38 Result:", result)


In [ ]:
# Q39: Count Unique Values in an Array
# Difficulty: L1

result = None

print("Q39 Result:", result)


In [ ]:
# Q40: Bin a Numeric Column into Categories
# Difficulty: L3

result = None

print("Q40 Result:", result)


In [ ]:
# Q41: Create a New Column from Existing Columns
# Difficulty: L3

result = None

print("Q41 Result:", result)


In [ ]:
# Q42: Probabilistic Sampling from a Categorical Array
# Difficulty: L3

result = None

print("Q42 Result:", result)


In [ ]:
# Q43: Get the Second Largest Value by Group
# Difficulty: L2

result = None

print("Q43 Result:", result)


In [ ]:
# Q44: Sort a 2D Array by a Column
# Difficulty: L2

result = None

print("Q44 Result:", result)


In [ ]:
# Q45: Find the Most Frequent Value in an Array
# Difficulty: L2

result = None

print("Q45 Result:", result)


In [ ]:
# Q46: Find the First Occurrence Greater Than a Value
# Difficulty: L2

result = None

print("Q46 Result:", result)


In [ ]:
# Q47: Clip Array Values to a Range
# Difficulty: L2

result = None

print("Q47 Result:", result)


In [ ]:
# Q48: Get the Positions of Top N Values
# Difficulty: L2

import numpy as np
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

result = None

print("Q48 Result:", result)


In [ ]:
# Q49: Compute Row-Wise Counts of All Possible Values
# Difficulty: L4

import numpy as np
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))
print(arr)

result = None

print("Q49 Result:", result)


In [ ]:
# Q50: Flatten an Array of Arrays into a 1D Array
# Difficulty: L2

result = None

print("Q50 Result:", result)


In [ ]:
# Q51: Generate One-Hot Encodings for an Array
# Difficulty: L3

result = None

print("Q51 Result:", result)


In [ ]:
# Q52: Create Row Numbers Grouped by a Categorical Variable
# Difficulty: L3

result = None

print("Q52 Result:", result)


In [ ]:
# Q53: Create Group IDs from a Categorical Variable
# Difficulty: L3

result = None

print("Q53 Result:", result)


In [ ]:
# Q54: Rank Items in a 1D Array
# Difficulty: L3

result = None

print("Q54 Result:", result)


In [ ]:
# Q55: Rank Items in a Multidimensional Array
# Difficulty: L3

result = None

print("Q55 Result:", result)


In [ ]:
# Q56: Find the Maximum Value in Each Row
# Difficulty: L2

result = None

print("Q56 Result:", result)


In [ ]:
# Q57: Compute the Min-by-Max Ratio for Each Row
# Difficulty: L2

result = None

print("Q57 Result:", result)


In [ ]:
# Q58: Find Duplicate Records in an Array
# Difficulty: L3

result = None

print("Q58 Result:", result)


In [ ]:
# Q59: Find the Grouped Mean
# Difficulty: L3

result = None

print("Q59 Result:", result)


In [ ]:
# Q60: Convert a PIL Image to a NumPy Array
# Difficulty: L3

import numpy as np
from io import BytesIO
from PIL import Image
import PIL, requests

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

result = None

print("Q60 Result:", result)


In [ ]:
# Q61: Drop All Missing Values from a 1D Array
# Difficulty: L2

result = None

print("Q61 Result:", result)


In [ ]:
# Q62: Compute the Euclidean Distance Between Two Arrays
# Difficulty: L3

import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

result = None

print("Q62 Result:", result)


In [ ]:
# Q63: Find All Local Maxima (Peaks) in a 1D Array
# Difficulty: L4

import numpy as np
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

result = None

print("Q63 Result:", result)


In [ ]:
# Q64: Subtract a 1D Array from a 2D Array Row-Wise
# Difficulty: L2

result = None

print("Q64 Result:", result)


In [ ]:
# Q65: Find the Index of the N'th Repetition of a Value
# Difficulty: L3

result = None

print("Q65 Result:", result)


In [ ]:
# Q66: Convert NumPy datetime64 to Python datetime
# Difficulty: L3

import numpy as np
dt64 = np.datetime64('2018-02-25 22:10:10')
print(dt64)

result = None

print("Q66 Result:", result)


In [ ]:
# Q67: Compute the Moving Average of an Array
# Difficulty: L3

import numpy as np
np.random.seed(100)
Z = np.random.randint(10, size=10)
print(Z)

result = None

print("Q67 Result:", result)


In [ ]:
# Q68: Create an Array Sequence Given Start, Length, and Step
# Difficulty: L2

import numpy as np
length = 10
start = 5
step = 3

result = None

print("Q68 Result:", result)


In [ ]:
# Q69: Fill in Missing Dates in an Irregular Date Series
# Difficulty: L3

import numpy as np
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

result = None

print("Q69 Result:", result)


In [ ]:
# Q70: Create Strides from a 1D Array
# Difficulty: L4

result = None

print("Q70 Result:", result)


In [ ]:
# Q71: How to create an array using a function of its row and column indices?
# Difficulty: L3

result = None

print("Q71 Result:", result)


In [ ]:
# Q72: How does array broadcasting work?
# Difficulty: L2

result = None

print("Q72 Result:", result)


In [ ]:
# Q73: How to create coordinate grids with np.meshgrid?
# Difficulty: L2

result = None

print("Q73 Result:", result)


In [ ]:
# Q74: How to standardize columns of a 2D array (zero mean, unit variance)?
# Difficulty: L2

result = None

print("Q74 Result:", result)


In [ ]:
# Q75: How to create and use structured arrays?
# Difficulty: L3

result = None

print("Q75 Result:", result)


In [ ]:
# Q76: How to use fancy indexing to select specific elements?
# Difficulty: L2

result = None

print("Q76 Result:", result)


In [ ]:
# Q77: How to compute cumulative sum and cumulative product?
# Difficulty: L2

result = None

print("Q77 Result:", result)


In [ ]:
# Q78: How to compute cumulative sum along a specific axis of a 2D array?
# Difficulty: L2

result = None

print("Q78 Result:", result)


In [ ]:
# Q79: How to compute a dot product using np.einsum?
# Difficulty: L2

result = None

print("Q79 Result:", result)


In [ ]:
# Q80: How to multiply two matrices using np.einsum?
# Difficulty: L2

result = None

print("Q80 Result:", result)


In [ ]:
# Q81: How to apply a custom function to every row or column of an array?
# Difficulty: L2

result = None

print("Q81 Result:", result)


In [ ]:
# Q82: How to get the rank of each element in an array?
# Difficulty: L3

result = None

print("Q82 Result:", result)


In [ ]:
# Q83: How to compute matrix determinant and inverse?
# Difficulty: L2

import numpy as np
A = np.array([[1, 2], [3, 4]])

result = None

print("Q83 Result:", result)


In [ ]:
# Q84: How to solve a system of linear equations with NumPy?
# Difficulty: L2

import numpy as np
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

result = None

print("Q84 Result:", result)


In [ ]:
# Q85: How to compute eigenvalues and eigenvectors?
# Difficulty: L3

import numpy as np
A = np.array([[4, -2], [1, 1]])

result = None

print("Q85 Result:", result)


In [ ]:
# Q86: How to fit a polynomial curve to noisy data?
# Difficulty: L3

import numpy as np
np.random.seed(42)
x = np.linspace(0, 5, 10)
y = 2*x**2 - 3*x + 1 + np.random.randn(10)*0.5

result = None

print("Q86 Result:", result)


In [ ]:
# Q87: How to select rows with a boolean mask and specific columns at the same time?
# Difficulty: L3

import numpy as np
a = np.arange(20).reshape(4, 5)
mask = np.array([True, False, True, False])
print('Array:')
print(a)

result = None

print("Q87 Result:", result)


In [ ]:
# Q88: How to compute the outer product of two vectors?
# Difficulty: L2

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = None

print("Q88 Result:", result)


In [ ]:
# Q89: How to compute a rolling/moving average of a 1D array?
# Difficulty: L3

import numpy as np
np.random.seed(42)
a = np.random.randint(1, 20, size=10)
print('Array:', a)

result = None

print("Q89 Result:", result)


In [ ]:
# Q90: How to rotate a 2D array (like an image)?
# Difficulty: L1

import numpy as np
img = np.arange(12).reshape(3, 4)
print('Original:')
print(img)

result = None

print("Q90 Result:", result)


In [ ]:
# Q91: How to flip an array horizontally and vertically?
# Difficulty: L1

result = None

print("Q91 Result:", result)


In [ ]:
# Q92: How to pad an array with zeros on all sides?
# Difficulty: L1

import numpy as np
a = np.ones((3, 3))

result = None

print("Q92 Result:", result)


In [ ]:
# Q93: How to create sliding windows over an array?
# Difficulty: L4

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
a = np.arange(10)

result = None

print("Q93 Result:", result)


In [ ]:
# Q94: How to compute min-max normalization to scale values between 0 and 1?
# Difficulty: L2

import numpy as np
np.random.seed(42)
a = np.random.randint(1, 100, size=(5, 3))
print('Original:')
print(a)

result = None

print("Q94 Result:", result)


In [ ]:
# Q95: How to compute a weighted average?
# Difficulty: L2

result = None

print("Q95 Result:", result)


In [ ]:
# Q96: How to find the top-k similar items using cosine similarity?
# Difficulty: L3

import numpy as np
np.random.seed(42)
items = np.random.rand(5, 4)
query = np.random.rand(4)
print('Items shape:', items.shape)
print('Query:', np.round(query, 3))

result = None

print("Q96 Result:", result)


In [ ]:
# Q97: How to compute the covariance matrix of a dataset?
# Difficulty: L3

result = None

print("Q97 Result:", result)


In [ ]:
# Q98: How to perform one-step PCA using eigendecomposition?
# Difficulty: L4

result = None

print("Q98 Result:", result)


In [ ]:
# Q99: How to compute 2D sliding windows over a matrix?
# Difficulty: L4

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
a = np.arange(25).reshape(5, 5)
print('Array:')
print(a)

result = None

print("Q99 Result:", result)


In [ ]:
# Q100: How to do batch matrix multiplication with np.einsum?
# Difficulty: L4

result = None

print("Q100 Result:", result)


In [ ]:
# Q101: How to compute a pairwise Euclidean distance matrix without loops?
# Difficulty: L4

result = None

print("Q101 Result:", result)
