<h1>Question 1</h1>

In [1]:
import mysql.connector

def fetch(cursor,chunk_size = 2000):
    while True:
        results = cursor.fetchmany(chunk_size)
        if not results:
            break
        for row in results:
            yield row

def main():
    db_config = {
        "host":"localhost",
        "user":"root",
        "password":"sasivan",
        "database":"employees"
    }
    try:
        conn = mysql.connector.connect(**db_config)
        cursor = conn.cursor(dictionary = True)
        print("Executing -")
        cursor.execute("select emp_no,salary,from_date from salaries;")

        salary_stream = fetch(cursor,chunk_size = 2000)

        count = 0
        total_salary = 0
        print("Processing records -")
        for record in salary_stream:
            count += 1
            total_salary += record["salary"]
        print(f"Record - {count} \nAvg salary - ${total_salary/count:.2f}")
    except mysql.Connector.Error as err:
        print(f"Error - {err}")
    finally:
        if 'conn' in locals() and conn.is_connected():
            cursor.close()
            conn.close()
            print("Exit")
if __name__ == "__main__":
    main()

Executing -
Processing records -
Record - 2844047 
Avg salary - $63810.74
Exit


<h1>Question 2</h1>

In [3]:
from abc import ABC , abstractmethod

class Person(ABC):
    @abstractmethod
    def get_gender(self):
        pass
class Male(Person):
    def get_gender(self):
        print("Male")
class Female(Person):
    def get_gender(self):
        print("Female")
if __name__ == "__main__":
    person1 = Male()
    person2 = Female()

    person1.get_gender()
    person2.get_gender()

    try:
        p_ab = Person()
    except TypeError as err:
        print("Error",err)

Male
Female
Error Can't instantiate abstract class Person without an implementation for abstract method 'get_gender'


<h1>Question 3</h1>

In [5]:
def remove_duplicate(seq):
    seen = set()
    result = []
    for i in seq:
        if i not in seen:
            seen.add(i)
            result.append(i)
    return result

original_list = [12, 24, 35, 24, 88, 120, 155, 88, 120, 155]

res = remove_duplicate(original_list)
print(f"Original - {original_list}")
print(f"Unique - {res}")

Original - [12, 24, 35, 24, 88, 120, 155, 88, 120, 155]
Unique - [12, 24, 35, 88, 120, 155]


<h1>Question 4</h1>

In [ ]:
#%pip install numpy
import numpy as np
#print([[[0 for _ in range(2)] for _ in range(2)] for _ in range(2)])
res = np.zeros((3,5,8),dtype=int)
print(res)


[[[0, 0], [0, 0]], [[0, 0], [0, 0]]]
[[[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]]


<h1>Question 5</h1>

In [11]:
def binary_search(arr,t):
    l = 0
    r = len(arr) - 1
    while l <= r:
        m = (r+l)//2
        if arr[m] > t:  r = m - 1
        elif arr[m] < t:    l = m + 1
        else: return m
    return -1
if __name__ == "__main__":
    sorted_list = [12, 24, 35, 88, 120, 155]
    search_item = 88

    result = binary_search(sorted_list, search_item)
    print(result)

3


<h1>Question 6</h1>

In [17]:
def check(n):
    for i in range(n+1):
        if i%5 ==0 and i%7 == 0:
            yield i
if __name__ == "__main__":
    n = int(input("Enter no - "))
    res = " , ".join(str(N) for N in check(n))
    print(res)

0 , 35 , 70 , 105


<h1>Question 7</h1>

In [19]:
def name(s):
    data = s.split("@")[1]
    return data.split('.')[0]
if __name__ == "__main__":
    s = "vishal.agnihotri@datagrokr.co"
    if '@' in s and '.' in s:
        res = name(s)
    print(res)

datagrokr


<h1>Question 8</h1>

In [20]:
print(list(map(lambda x: x**2, range(1,21))))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


<h1>Question 9</h1>

In [21]:
import os

def tree(path, space=""):
    files = os.listdir(path)

    for file in files:
        print(space + "|--", file)

        full_path = os.path.join(path, file)

        if os.path.isdir(full_path):
            tree(full_path, space + "    ")

folder = "C:\Work\Python\Assignments"
tree(folder)


|-- main.ipynb
|-- test_db
    |-- .git
        |-- config
        |-- description
        |-- HEAD
        |-- hooks
            |-- applypatch-msg.sample
            |-- commit-msg.sample
            |-- fsmonitor-watchman.sample
            |-- post-update.sample
            |-- pre-applypatch.sample
            |-- pre-commit.sample
            |-- pre-merge-commit.sample
            |-- pre-push.sample
            |-- pre-rebase.sample
            |-- pre-receive.sample
            |-- prepare-commit-msg.sample
            |-- push-to-checkout.sample
            |-- sendemail-validate.sample
            |-- update.sample
        |-- index
        |-- info
            |-- exclude
        |-- logs
            |-- HEAD
            |-- refs
                |-- heads
                    |-- master
                |-- remotes
                    |-- origin
                        |-- HEAD
        |-- objects
            |-- info
            |-- pack
                |-- pack-f3f221aad8d7

<>:14: SyntaxWarning: invalid escape sequence '\W'
<>:14: SyntaxWarning: invalid escape sequence '\W'
C:\Users\Sasiv\AppData\Local\Temp\ipykernel_2880\1512529786.py:14: SyntaxWarning: invalid escape sequence '\W'
  folder = "C:\Work\Python\Assignments"


<h1>Question 10</h1>

In [ ]:
class ReverseIter:
    def __init__(self,data):
        self.data = data
        self.ind = len(data) - 1
    def __iter__(self):
        return self
    def __next__(self):
        if self.ind >= 0:
            item = self.data[self.ind]
            self.ind -= 1
            return item
        else:
            raise StopIteration
if __name__ == "__main__":
    res = ReverseIter([10, 20, 30, 40, 50])
    print(*res)

50 40 30 20 10



<h1>Question 11</h1>

In [29]:
import urllib.request
import re

url = "https://datagrokr.co/"

html = urllib.request.urlopen(url).read().decode()

text = re.sub("<.*?>", "", html)

print(text)




	
	
	
	
	img:is([sizes="auto" i], [sizes^="auto," i]) { contain-intrinsic-size: 3000px 1500px }
	
	
	IT Strategy and Consulting Services in Bangalore | DataGrokr
	
	
	
	
	
	
	
	
	
	
	
	
	{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://datagrokr.co/","url":"https://datagrokr.co/","name":"IT Strategy and Consulting Services in Bangalore | DataGrokr","isPartOf":{"@id":"https://datagrokr.co/#website"},"datePublished":"2021-05-05T18:30:43+00:00","dateModified":"2022-11-24T04:37:04+00:00","description":"DataGrokr provides a comprehensive range of consulting services and products to assist businesses in utilizing technology to compete in the world.","breadcrumb":{"@id":"https://datagrokr.co/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://datagrokr.co/"]}]},{"@type":"BreadcrumbList","@id":"https://datagrokr.co/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home"}]},{"@type":"WebSite","@id":